#ifndef PROTOCOL_H
#define PROTOCOL_H

#define MESSAGE_DELIMITER '\\'

enum MESSAGE_STATUS { REQUEST, RESPONSE, INVALID_STATUS };

enum MESSAGE_TYPE {
  LOGIN,
  REGISTER,
  PEDIDO_MENU,
  PEDIDO_CREATE,
  PEDIDO_STATE,
  PEDIDO_LIST,
  PEDIDO_CANCEL,
  CLOSE,
  INVALID_TYPE // Used when deserializing
};

#endif // PROTOCOL_H
